- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- README.md
This provides information on the code of conduct and how folks can contribute to further development. Please let me know if there are other details you'd like to provide to outside contributors.
> Add contribution guidelines. Closes #4.

- backend/README.md
Updated images link which was broken due to old branch reference
> updated images link

- clever-crop/src/app/advice/advice.component.html
- clever-crop/src/app/advice/advice.component.scss
- clever-crop/src/app/advice/advice.component.ts
- clever-crop/src/app/measure-soil/measure-soil.component.ts
> Sensor connect

- clever-crop/src/app/advice/advice.component.html
- clever-crop/src/app/advice/advice.component.ts
- clever-crop/src/app/app.module.ts
- clever-crop/src/app/growth-stage/growth-stage.component.ts
- clever-crop/src/app/my-crops/my-crops.component.html
- clever-crop/src/app/my-crops/my-crops.component.ts
1. route to my crop from advice and vice versa
2. rm the crop
> rm the crop & route advice to my crop

- clever-crop/src/app/components/advice/advice.component.html
- clever-crop/src/app/components/advice/advice.component.scss
- clever-crop/src/app/components/measure-soil/measure-soil.component.html
- clever-crop/src/app/components/my-crops/my-crops.component.html
- clever-crop/src/app/components/my-crops/my-crops.component.ts
- implement the "Add your first corp" page when no crops was select
- modify the crop card layout for the crop description and menu
> Dev yz - update my crop component

- clever-crop/src/app/components/advice/advice.component.html
- clever-crop/src/app/components/advice/advice.component.scss
make the fab responsive in the advice component
> make the fab responsive in the advice component

- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
- liquid-prep-app/src/app/components/select-crop/select-crop.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.module.ts
add a spinner before getting the list of crops from the backend service
> add spinner before getting the list of crops from backend service

- liquid-prep-app/README.md
- liquid-prep-app/src/config.json.sample
adding sample config.json file to update the backend service endpoint url
> adding sample config.json file 

- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/service/WaterAdviceService.ts
- liquid-prep-app/src/app/service/WeatherDataService.ts
> modified water advise logics

- CONTRIBUTING.md
updating with TSC members and additional contributing guide
> updating with TSC members and additional contributing guide

- CONTRIBUTING.md
updated bug report and new feature links
> updated bug report and new feature links

- CONTRIBUTING.md
added Brian and Jason to TSC member list
> added Brian and Jason to TSC member list

- .github/pull_request_template.md
Signed-off-by: Daniel Krook <krook@us.ibm.com>
> Adding a pull request template.

- backend/liquid-prep-cf/package.json
- backend/liquid-prep-cf/webpack.config.js
The backend project was not able to bundle due to missing webpack plugin dependency
Patch
No
Add any other technical detail or considerations here.
> add missing webpack dependency

- backend/README.md
- backend/liquid-prep-cf/bin/deploy.js
Suggestions to make it easier to get started with the back end from my experiences including:
- making it easier to setup .env file
- fix typo URL
- fix error in deploy script
minor
Not related to open issue.
Applies only to backend
> Changes documentation and deply script to help others to get started with backend

- liquid-prep-app/package-lock.json
- liquid-prep-app/src/app/components/growth-stage/growth-stage.component.ts
- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/my-crops/my-crops.component.scss
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.ts
- liquid-prep-app/src/app/service/CropDataService.ts
- liquid-prep-app/src/app/service/DataService.ts
- liquid-prep-app/src/app/service/GeoLocationService.ts
- liquid-prep-app/src/app/service/WeatherDataService.ts
Add error handling to web app.
- Also put in a suggestion on the My Crops page to display the High and Low Forecast Temperatures to make it clear that what is being displayed rather than the current temperature.
Minor
https://github.com/Call-for-Code/Liquid-Prep/issues/63
n/a
> Handle backend API errors and show valid error message in UI #63

- CONTRIBUTING.md
- README.md
Updated the button to join the overall community, not just Slack
> Update License/Community buttons

- liquid-prep-app/README.md
README Update
Patch
NO
Add any other technical detail or considerations here.
> update reference to file name to "src/config-sample.json"

- README.md
- liquid-prep-app/README.md
> update app url

- CNM/Particle Sensor Schematics/README.md
- CNM/README.md
- README.md
- backend/README.md
- liquid-prep-app/README.md
fixed typos in readmes
patch
no
> Fix typos in readmes

- liquid-prep-app/src/app/components/advice/advice.component.html
- sync fonts for all the advice page elements
- removed soil moisture percent value as we already show in the previous screen
patch
> sync fonts for all the advice page elements

- backend/liquid-prep-cf/package-lock.json
update package-lock.json file
Patch
> update package lock json file

- liquid-prep-app/README.md
A clear and concise description of what you changed.
Patch, minor, or major.
Please provide the link.
Add any other technical detail or considerations here.
> notes on using prefix for nested contents upload

- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/models/api/WeatherResponse.ts
- liquid-prep-app/src/app/service/WeatherDataService.ts
fix the null temperature value after 3 pm local time in the my-crops page
minor
#61 
The day time temperature null values after the 3 pm local time is configured by TWC design for the daily forecast API.
> Fix null temp values

- README.md
- liquid-prep-app/README.md
- Update  App URL
- Update setup docs readme URL
Patch
> App link update

- .github/workflows/projectCI.yml
- CNM/README.md
- README.md
- backend/README.md
- liquid-prep-app/README.md
Fixed the paths for URLs and images after migration to new workspace
Patch
> fixed the paths for URLs and images after migration to new workspace

- README.md
removed references of 'low literate' and 'developing countries' to be inclusive and welcoming, which is in line with our Code of Conduct. this solution is for everyone everywhere :) 
also cleaned up text.
this is an essential edit for inclusivity and accuracy.
not related to an open issue.
i'm the technical writer that Rory brought on board to help with documentation for launch and presentations.
> Revise text for README.md
